# src/agent/overworld/map_enums.py

from enum import Enum

def _might_be_map_coordinates(value) -> bool:
    return isinstance(value, tuple) and len(value) == 2 and all(isinstance(x, int) for x in value)

class MapGroupFRLG(Enum):

    Link = 0
    Dungeons = 1
    SpecialArea = 2
    TownsAndRoutes = 3
    IndoorPallet = 4
    IndoorViridian = 5
    IndoorPewter = 6
    IndoorCerulean = 7
    IndoorLavender = 8
    IndoorVermilion = 9
    IndoorCeladon = 10
    IndoorFuchsia = 11
    IndoorCinnabar = 12
    IndoorIndigoPlateau = 13
    IndoorSaffron = 14
    IndoorRoute2 = 15
    IndoorRoute4 = 16
    IndoorRoute5 = 17
    IndoorRoute6 = 18
    IndoorRoute7 = 19
    IndoorRoute8 = 20
    IndoorRoute10 = 21
    IndoorRoute11 = 22
    IndoorRoute12 = 23
    IndoorRoute15 = 24
    IndoorRoute16 = 25
    IndoorRoute18 = 26
    IndoorRoute19 = 27
    IndoorRoute22 = 28
    IndoorRoute23 = 29
    IndoorRoute25 = 30
    IndoorSevenIsland = 31
    IndoorOneIsland = 32
    IndoorTwoIsland = 33
    IndoorThreeIsland = 34
    IndoorFourIsland = 35
    IndoorFiveIsland = 36
    IndoorSixIsland = 37
    IndoorThreeIslandRoute = 38
    IndoorFiveIslandRoute = 39
    IndoorTwoIslandRoute = 40
    IndoorSixIslandRoute = 41
    IndoorSevenIslandRoute = 42

    def __contains__(self, item):
        # If "item" is (group, number), we match the group
        if _might_be_map_coordinates(item):
            return self.value == item[0]
        return NotImplemented

class MapFRLG(Enum):

    # Link
    BATTLE_COLOSSEUM_2P = (0, 0)
    TRADE_CENTER = (0, 1)
    RECORD_CORNER = (0, 2)
    BATTLE_COLOSSEUM_4P = (0, 3)
    UNION_ROOM = (0, 4)

    # Dungeons
    VIRIDIAN_FOREST = (1, 0)
    MT_MOON_1F = (1, 1)
    MT_MOON_B1F = (1, 2)
    MT_MOON_B2F = (1, 3)
    SSANNE_EXTERIOR = (1, 4)
    SSANNE_1F_CORRIDOR = (1, 5)
    SSANNE_2F_CORRIDOR = (1, 6)
    SSANNE_3F_CORRIDOR = (1, 7)
    SSANNE_B1F_CORRIDOR = (1, 8)
    SSANNE_DECK = (1, 9)
    SSANNE_KITCHEN = (1, 10)
    SSANNE_CAPTAINS_OFFICE = (1, 11)
    SSANNE_1F_ROOM1 = (1, 12)
    SSANNE_1F_ROOM2 = (1, 13)
    SSANNE_1F_ROOM3 = (1, 14)
    SSANNE_1F_ROOM4 = (1, 15)
    SSANNE_1F_ROOM5 = (1, 16)
    SSANNE_1F_ROOM7 = (1, 17)
    SSANNE_2F_ROOM1 = (1, 18)
    SSANNE_2F_ROOM2 = (1, 19)
    SSANNE_2F_ROOM3 = (1, 20)
    SSANNE_2F_ROOM4 = (1, 21)
    SSANNE_2F_ROOM5 = (1, 22)
    SSANNE_2F_ROOM6 = (1, 23)
    SSANNE_B1F_ROOM1 = (1, 24)
    SSANNE_B1F_ROOM2 = (1, 25)
    SSANNE_B1F_ROOM3 = (1, 26)
    SSANNE_B1F_ROOM4 = (1, 27)
    SSANNE_B1F_ROOM5 = (1, 28)
    SSANNE_1F_ROOM6 = (1, 29)
    UNDERGROUND_PATH_NORTH_ENTRANCE = (1, 30)
    UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL = (1, 31)
    UNDERGROUND_PATH_SOUTH_ENTRANCE = (1, 32)
    UNDERGROUND_PATH_WEST_ENTRANCE = (1, 33)
    UNDERGROUND_PATH_EAST_WEST_TUNNEL = (1, 34)
    UNDERGROUND_PATH_EAST_ENTRANCE = (1, 35)
    DIGLETTS_CAVE_NORTH_ENTRANCE = (1, 36)
    DIGLETTS_CAVE_B1F = (1, 37)
    DIGLETTS_CAVE_SOUTH_ENTRANCE = (1, 38)
    VICTORY_ROAD_1F = (1, 39)
    VICTORY_ROAD_2F = (1, 40)
    VICTORY_ROAD_3F = (1, 41)
    ROCKET_HIDEOUT_B1F = (1, 42)
    ROCKET_HIDEOUT_B2F = (1, 43)
    ROCKET_HIDEOUT_B3F = (1, 44)
    ROCKET_HIDEOUT_B4F = (1, 45)
    ROCKET_HIDEOUT_ELEVATOR = (1, 46)
    SILPH_CO_1F = (1, 47)
    SILPH_CO_2F = (1, 48)
    SILPH_CO_3F = (1, 49)
    SILPH_CO_4F = (1, 50)
    SILPH_CO_5F = (1, 51)
    SILPH_CO_6F = (1, 52)
    SILPH_CO_7F = (1, 53)
    SILPH_CO_8F = (1, 54)
    SILPH_CO_9F = (1, 55)
    SILPH_CO_10F = (1, 56)
    SILPH_CO_11F = (1, 57)
    SILPH_CO_ELEVATOR = (1, 58)
    POKEMON_MANSION_1F = (1, 59)
    POKEMON_MANSION_2F = (1, 60)
    POKEMON_MANSION_3F = (1, 61)
    POKEMON_MANSION_B1F = (1, 62)
    SAFARI_ZONE_CENTER = (1, 63)
    SAFARI_ZONE_EAST = (1, 64)
    SAFARI_ZONE_NORTH = (1, 65)
    SAFARI_ZONE_WEST = (1, 66)
    SAFARI_ZONE_CENTER_REST_HOUSE = (1, 67)
    SAFARI_ZONE_EAST_REST_HOUSE = (1, 68)
    SAFARI_ZONE_NORTH_REST_HOUSE = (1, 69)
    SAFARI_ZONE_WEST_REST_HOUSE = (1, 70)
    SAFARI_ZONE_SECRET_HOUSE = (1, 71)
    CERULEAN_CAVE_1F = (1, 72)
    CERULEAN_CAVE_2F = (1, 73)
    CERULEAN_CAVE_B1F = (1, 74)
    POKEMON_LEAGUE_LORELEIS_ROOM = (1, 75)
    POKEMON_LEAGUE_BRUNOS_ROOM = (1, 76)
    POKEMON_LEAGUE_AGATHAS_ROOM = (1, 77)
    POKEMON_LEAGUE_LANCES_ROOM = (1, 78)
    POKEMON_LEAGUE_CHAMPIONS_ROOM = (1, 79)
    POKEMON_LEAGUE_HALL_OF_FAME = (1, 80)
    ROCK_TUNNEL_1F = (1, 81)
    ROCK_TUNNEL_B1F = (1, 82)
    SEAFOAM_ISLANDS_1F = (1, 83)
    SEAFOAM_ISLANDS_B1F = (1, 84)
    SEAFOAM_ISLANDS_B2F = (1, 85)
    SEAFOAM_ISLANDS_B3F = (1, 86)
    SEAFOAM_ISLANDS_B4F = (1, 87)
    POKEMON_TOWER_1F = (1, 88)
    POKEMON_TOWER_2F = (1, 89)
    POKEMON_TOWER_3F = (1, 90)
    POKEMON_TOWER_4F = (1, 91)
    POKEMON_TOWER_5F = (1, 92)
    POKEMON_TOWER_6F = (1, 93)
    POKEMON_TOWER_7F = (1, 94)
    POWER_PLANT = (1, 95)
    MT_EMBER_RUBY_PATH_B4F = (1, 96)
    MT_EMBER_EXTERIOR = (1, 97)
    MT_EMBER_SUMMIT_PATH_1F = (1, 98)
    MT_EMBER_SUMMIT_PATH_2F = (1, 99)
    MT_EMBER_SUMMIT_PATH_3F = (1, 100)
    MT_EMBER_SUMMIT = (1, 101)
    MT_EMBER_RUBY_PATH_B5F = (1, 102)
    MT_EMBER_RUBY_PATH_1F = (1, 103)
    MT_EMBER_RUBY_PATH_B1F = (1, 104)
    MT_EMBER_RUBY_PATH_B2F = (1, 105)
    MT_EMBER_RUBY_PATH_B3F = (1, 106)
    MT_EMBER_RUBY_PATH_B1F_STAIRS = (1, 107)
    MT_EMBER_RUBY_PATH_B2F_STAIRS = (1, 108)
    THREE_ISLAND_BERRY_FOREST = (1, 109)
    FOUR_ISLAND_ICEFALL_CAVE_ENTRANCE = (1, 110)
    FOUR_ISLAND_ICEFALL_CAVE_1F = (1, 111)
    FOUR_ISLAND_ICEFALL_CAVE_B1F = (1, 112)
    FOUR_ISLAND_ICEFALL_CAVE_BACK = (1, 113)
    FIVE_ISLAND_ROCKET_WAREHOUSE = (1, 114)
    SIX_ISLAND_DOTTED_HOLE_1F = (1, 115)
    SIX_ISLAND_DOTTED_HOLE_B1F = (1, 116)
    SIX_ISLAND_DOTTED_HOLE_B2F = (1, 117)
    SIX_ISLAND_DOTTED_HOLE_B3F = (1, 118)
    SIX_ISLAND_DOTTED_HOLE_B4F = (1, 119)
    SIX_ISLAND_DOTTED_HOLE_SAPPHIRE_ROOM = (1, 120)
    SIX_ISLAND_PATTERN_BUSH = (1, 121)
    SIX_ISLAND_ALTERING_CAVE = (1, 122)

    # SpecialArea
    NAVEL_ROCK_EXTERIOR = (2, 0)
    TRAINER_TOWER_1F = (2, 1)
    TRAINER_TOWER_2F = (2, 2)
    TRAINER_TOWER_3F = (2, 3)
    TRAINER_TOWER_4F = (2, 4)
    TRAINER_TOWER_5F = (2, 5)
    TRAINER_TOWER_6F = (2, 6)
    TRAINER_TOWER_7F = (2, 7)
    TRAINER_TOWER_8F = (2, 8)
    TRAINER_TOWER_ROOF = (2, 9)
    TRAINER_TOWER_LOBBY = (2, 10)
    TRAINER_TOWER_ELEVATOR = (2, 11)
    FIVE_ISLAND_LOST_CAVE_ENTRANCE = (2, 12)
    FIVE_ISLAND_LOST_CAVE_ROOM1 = (2, 13)
    FIVE_ISLAND_LOST_CAVE_ROOM2 = (2, 14)
    FIVE_ISLAND_LOST_CAVE_ROOM3 = (2, 15)
    FIVE_ISLAND_LOST_CAVE_ROOM4 = (2, 16)
    FIVE_ISLAND_LOST_CAVE_ROOM5 = (2, 17)
    FIVE_ISLAND_LOST_CAVE_ROOM6 = (2, 18)
    FIVE_ISLAND_LOST_CAVE_ROOM7 = (2, 19)
    FIVE_ISLAND_LOST_CAVE_ROOM8 = (2, 20)
    FIVE_ISLAND_LOST_CAVE_ROOM9 = (2, 21)
    FIVE_ISLAND_LOST_CAVE_ROOM10 = (2, 22)
    FIVE_ISLAND_LOST_CAVE_ROOM11 = (2, 23)
    FIVE_ISLAND_LOST_CAVE_ROOM12 = (2, 24)
    FIVE_ISLAND_LOST_CAVE_ROOM13 = (2, 25)
    FIVE_ISLAND_LOST_CAVE_ROOM14 = (2, 26)
    SEVEN_ISLAND_TANOBY_RUINS_MONEAN_CHAMBER = (2, 27)
    SEVEN_ISLAND_TANOBY_RUINS_LIPTOO_CHAMBER = (2, 28)
    SEVEN_ISLAND_TANOBY_RUINS_WEEPTH_CHAMBER = (2, 29)
    SEVEN_ISLAND_TANOBY_RUINS_DILFORD_CHAMBER = (2, 30)
    SEVEN_ISLAND_TANOBY_RUINS_SCUFIB_CHAMBER = (2, 31)
    SEVEN_ISLAND_TANOBY_RUINS_RIXY_CHAMBER = (2, 32)
    SEVEN_ISLAND_TANOBY_RUINS_VIAPOIS_CHAMBER = (2, 33)
    THREE_ISLAND_DUNSPARCE_TUNNEL = (2, 34)
    SEVEN_ISLAND_SEVAULT_CANYON_TANOBY_KEY = (2, 35)
    NAVEL_ROCK_1F = (2, 36)
    NAVEL_ROCK_SUMMIT = (2, 37)
    NAVEL_ROCK_BASE = (2, 38)
    NAVEL_ROCK_SUMMIT_PATH_2F = (2, 39)
    NAVEL_ROCK_SUMMIT_PATH_3F = (2, 40)
    NAVEL_ROCK_SUMMIT_PATH_4F = (2, 41)
    NAVEL_ROCK_SUMMIT_PATH_5F = (2, 42)
    NAVEL_ROCK_BASE_PATH_B1F = (2, 43)
    NAVEL_ROCK_BASE_PATH_B2F = (2, 44)
    NAVEL_ROCK_BASE_PATH_B3F = (2, 45)
    NAVEL_ROCK_BASE_PATH_B4F = (2, 46)
    NAVEL_ROCK_BASE_PATH_B5F = (2, 47)
    NAVEL_ROCK_BASE_PATH_B6F = (2, 48)
    NAVEL_ROCK_BASE_PATH_B7F = (2, 49)
    NAVEL_ROCK_BASE_PATH_B8F = (2, 50)
    NAVEL_ROCK_BASE_PATH_B9F = (2, 51)
    NAVEL_ROCK_BASE_PATH_B10F = (2, 52)
    NAVEL_ROCK_BASE_PATH_B11F = (2, 53)
    NAVEL_ROCK_B1F = (2, 54)
    NAVEL_ROCK_FORK = (2, 55)
    BIRTH_ISLAND_EXTERIOR = (2, 56)
    ONE_ISLAND_KINDLE_ROAD_EMBER_SPA = (2, 57)
    BIRTH_ISLAND_HARBOR = (2, 58)
    NAVEL_ROCK_HARBOR = (2, 59)

    # TownsAndRoutes
    PALLET_TOWN = (3, 0)
    VIRIDIAN_CITY = (3, 1)
    PEWTER_CITY = (3, 2)
    CERULEAN_CITY = (3, 3)
    LAVENDER_TOWN = (3, 4)
    VERMILION_CITY = (3, 5)
    CELADON_CITY = (3, 6)
    FUCHSIA_CITY = (3, 7)
    CINNABAR_ISLAND = (3, 8)
    INDIGO_PLATEAU_EXTERIOR = (3, 9)
    SAFFRON_CITY = (3, 10)
    SAFFRON_CITY_CONNECTION = (3, 11)
    ONE_ISLAND = (3, 12)
    TWO_ISLAND = (3, 13)
    THREE_ISLAND = (3, 14)
    FOUR_ISLAND = (3, 15)
    FIVE_ISLAND = (3, 16)
    SEVEN_ISLAND = (3, 17)
    SIX_ISLAND = (3, 18)
    ROUTE1 = (3, 19)
    ROUTE2 = (3, 20)
    ROUTE3 = (3, 21)
    ROUTE4 = (3, 22)
    ROUTE5 = (3, 23)
    ROUTE6 = (3, 24)
    ROUTE7 = (3, 25)
    ROUTE8 = (3, 26)
    ROUTE9 = (3, 27)
    ROUTE10 = (3, 28)
    ROUTE11 = (3, 29)
    ROUTE12 = (3, 30)
    ROUTE13 = (3, 31)
    ROUTE14 = (3, 32)
    ROUTE15 = (3, 33)
    ROUTE16 = (3, 34)
    ROUTE17 = (3, 35)
    ROUTE18 = (3, 36)
    ROUTE19 = (3, 37)
    ROUTE20 = (3, 38)
    ROUTE21_NORTH = (3, 39)
    ROUTE21_SOUTH = (3, 40)
    ROUTE22 = (3, 41)
    ROUTE23 = (3, 42)
    ROUTE24 = (3, 43)
    ROUTE25 = (3, 44)
    ONE_ISLAND_KINDLE_ROAD = (3, 45)
    ONE_ISLAND_TREASURE_BEACH = (3, 46)
    TWO_ISLAND_CAPE_BRINK = (3, 47)
    THREE_ISLAND_BOND_BRIDGE = (3, 48)
    THREE_ISLAND_PORT = (3, 49)
    PROTOTYPE_SEVII_ISLE_6 = (3, 50)
    PROTOTYPE_SEVII_ISLE_7 = (3, 51)
    PROTOTYPE_SEVII_ISLE_8 = (3, 52)
    PROTOTYPE_SEVII_ISLE_9 = (3, 53)
    FIVE_ISLAND_RESORT_GORGEOUS = (3, 54)
    FIVE_ISLAND_WATER_LABYRINTH = (3, 55)
    FIVE_ISLAND_MEADOW = (3, 56)
    FIVE_ISLAND_MEMORIAL_PILLAR = (3, 57)
    SIX_ISLAND_OUTCAST_ISLAND = (3, 58)
    SIX_ISLAND_GREEN_PATH = (3, 59)
    SIX_ISLAND_WATER_PATH = (3, 60)
    SIX_ISLAND_RUIN_VALLEY = (3, 61)
    SEVEN_ISLAND_TRAINER_TOWER = (3, 62)
    SEVEN_ISLAND_SEVAULT_CANYON_ENTRANCE = (3, 63)
    SEVEN_ISLAND_SEVAULT_CANYON = (3, 64)
    SEVEN_ISLAND_TANOBY_RUINS = (3, 65)

    # IndoorPallet
    PALLET_TOWN_PLAYERS_HOUSE_1F = (4, 0)
    PALLET_TOWN_PLAYERS_HOUSE_2F = (4, 1)
    PALLET_TOWN_RIVALS_HOUSE = (4, 2)
    PALLET_TOWN_PROFESSOR_OAKS_LAB = (4, 3)

    # IndoorViridian
    VIRIDIAN_CITY_HOUSE = (5, 0)
    VIRIDIAN_CITY_GYM = (5, 1)
    VIRIDIAN_CITY_SCHOOL = (5, 2)
    VIRIDIAN_CITY_MART = (5, 3)
    VIRIDIAN_CITY_POKEMON_CENTER_1F = (5, 4)
    VIRIDIAN_CITY_POKEMON_CENTER_2F = (5, 5)

    # IndoorPewter
    PEWTER_CITY_MUSEUM_1F = (6, 0)
    PEWTER_CITY_MUSEUM_2F = (6, 1)
    PEWTER_CITY_GYM = (6, 2)
    PEWTER_CITY_MART = (6, 3)
    PEWTER_CITY_HOUSE1 = (6, 4)
    PEWTER_CITY_POKEMON_CENTER_1F = (6, 5)
    PEWTER_CITY_POKEMON_CENTER_2F = (6, 6)
    PEWTER_CITY_HOUSE2 = (6, 7)

    # IndoorCerulean
    CERULEAN_CITY_HOUSE1 = (7, 0)
    CERULEAN_CITY_HOUSE2 = (7, 1)
    CERULEAN_CITY_HOUSE3 = (7, 2)
    CERULEAN_CITY_POKEMON_CENTER_1F = (7, 3)
    CERULEAN_CITY_POKEMON_CENTER_2F = (7, 4)
    CERULEAN_CITY_GYM = (7, 5)
    CERULEAN_CITY_BIKE_SHOP = (7, 6)
    CERULEAN_CITY_MART = (7, 7)
    CERULEAN_CITY_HOUSE4 = (7, 8)
    CERULEAN_CITY_HOUSE5 = (7, 9)

    # IndoorLavender
    LAVENDER_TOWN_POKEMON_CENTER_1F = (8, 0)
    LAVENDER_TOWN_POKEMON_CENTER_2F = (8, 1)
    LAVENDER_TOWN_VOLUNTEER_POKEMON_HOUSE = (8, 2)
    LAVENDER_TOWN_HOUSE1 = (8, 3)
    LAVENDER_TOWN_HOUSE2 = (8, 4)
    LAVENDER_TOWN_MART = (8, 5)

    # IndoorVermilion
    VERMILION_CITY_HOUSE1 = (9, 0)
    VERMILION_CITY_POKEMON_CENTER_1F = (9, 1)
    VERMILION_CITY_POKEMON_CENTER_2F = (9, 2)
    VERMILION_CITY_POKEMON_FAN_CLUB = (9, 3)
    VERMILION_CITY_HOUSE2 = (9, 4)
    VERMILION_CITY_MART = (9, 5)
    VERMILION_CITY_GYM = (9, 6)
    VERMILION_CITY_HOUSE3 = (9, 7)

    # IndoorCeladon
    CELADON_CITY_DEPARTMENT_STORE_1F = (10, 0)
    CELADON_CITY_DEPARTMENT_STORE_2F = (10, 1)
    CELADON_CITY_DEPARTMENT_STORE_3F = (10, 2)
    CELADON_CITY_DEPARTMENT_STORE_4F = (10, 3)
    CELADON_CITY_DEPARTMENT_STORE_5F = (10, 4)
    CELADON_CITY_DEPARTMENT_STORE_ROOF = (10, 5)
    CELADON_CITY_DEPARTMENT_STORE_ELEVATOR = (10, 6)
    CELADON_CITY_CONDOMINIUMS_1F = (10, 7)
    CELADON_CITY_CONDOMINIUMS_2F = (10, 8)
    CELADON_CITY_CONDOMINIUMS_3F = (10, 9)
    CELADON_CITY_CONDOMINIUMS_ROOF = (10, 10)
    CELADON_CITY_CONDOMINIUMS_ROOF_ROOM = (10, 11)
    CELADON_CITY_POKEMON_CENTER_1F = (10, 12)
    CELADON_CITY_POKEMON_CENTER_2F = (10, 13)
    CELADON_CITY_GAME_CORNER = (10, 14)
    CELADON_CITY_GAME_CORNER_PRIZE_ROOM = (10, 15)
    CELADON_CITY_GYM = (10, 16)
    CELADON_CITY_RESTAURANT = (10, 17)
    CELADON_CITY_HOUSE1 = (10, 18)
    CELADON_CITY_HOTEL = (10, 19)

    # IndoorFuchsia
    FUCHSIA_CITY_SAFARI_ZONE_ENTRANCE = (11, 0)
    FUCHSIA_CITY_MART = (11, 1)
    FUCHSIA_CITY_SAFARI_ZONE_OFFICE = (11, 2)
    FUCHSIA_CITY_GYM = (11, 3)
    FUCHSIA_CITY_HOUSE1 = (11, 4)
    FUCHSIA_CITY_POKEMON_CENTER_1F = (11, 5)
    FUCHSIA_CITY_POKEMON_CENTER_2F = (11, 6)
    FUCHSIA_CITY_WARDENS_HOUSE = (11, 7)
    FUCHSIA_CITY_HOUSE2 = (11, 8)
    FUCHSIA_CITY_HOUSE3 = (11, 9)

    # IndoorCinnabar
    CINNABAR_ISLAND_GYM = (12, 0)
    CINNABAR_ISLAND_POKEMON_LAB_ENTRANCE = (12, 1)
    CINNABAR_ISLAND_POKEMON_LAB_LOUNGE = (12, 2)
    CINNABAR_ISLAND_POKEMON_LAB_RESEARCH_ROOM = (12, 3)
    CINNABAR_ISLAND_POKEMON_LAB_EXPERIMENT_ROOM = (12, 4)
    CINNABAR_ISLAND_POKEMON_CENTER_1F = (12, 5)
    CINNABAR_ISLAND_POKEMON_CENTER_2F = (12, 6)
    CINNABAR_ISLAND_MART = (12, 7)

    # IndoorIndigoPlateau
    INDIGO_PLATEAU_POKEMON_CENTER_1F = (13, 0)
    INDIGO_PLATEAU_POKEMON_CENTER_2F = (13, 1)

    # IndoorSaffron
    SAFFRON_CITY_COPYCATS_HOUSE_1F = (14, 0)
    SAFFRON_CITY_COPYCATS_HOUSE_2F = (14, 1)
    SAFFRON_CITY_DOJO = (14, 2)
    SAFFRON_CITY_GYM = (14, 3)
    SAFFRON_CITY_HOUSE = (14, 4)
    SAFFRON_CITY_MART = (14, 5)
    SAFFRON_CITY_POKEMON_CENTER_1F = (14, 6)
    SAFFRON_CITY_POKEMON_CENTER_2F = (14, 7)
    SAFFRON_CITY_MR_PSYCHICS_HOUSE = (14, 8)
    SAFFRON_CITY_POKEMON_TRAINER_FAN_CLUB = (14, 9)

    # IndoorRoute2
    ROUTE2_VIRIDIAN_FOREST_SOUTH_ENTRANCE = (15, 0)
    ROUTE2_HOUSE = (15, 1)
    ROUTE2_EAST_BUILDING = (15, 2)
    ROUTE2_VIRIDIAN_FOREST_NORTH_ENTRANCE = (15, 3)

    # IndoorRoute4
    ROUTE4_POKEMON_CENTER_1F = (16, 0)
    ROUTE4_POKEMON_CENTER_2F = (16, 1)

    # IndoorRoute5
    ROUTE5_POKEMON_DAY_CARE = (17, 0)
    ROUTE5_SOUTH_ENTRANCE = (17, 1)

    # IndoorRoute6
    ROUTE6_NORTH_ENTRANCE = (18, 0)
    ROUTE6_UNUSED_HOUSE = (18, 1)

    # IndoorRoute7
    ROUTE7_EAST_ENTRANCE = (19, 0)

    # IndoorRoute8
    ROUTE8_WEST_ENTRANCE = (20, 0)

    # IndoorRoute10
    ROUTE10_POKEMON_CENTER_1F = (21, 0)
    ROUTE10_POKEMON_CENTER_2F = (21, 1)

    # IndoorRoute11
    ROUTE11_EAST_ENTRANCE_1F = (22, 0)
    ROUTE11_EAST_ENTRANCE_2F = (22, 1)

    # IndoorRoute12
    ROUTE12_NORTH_ENTRANCE_1F = (23, 0)
    ROUTE12_NORTH_ENTRANCE_2F = (23, 1)
    ROUTE12_FISHING_HOUSE = (23, 2)

    # IndoorRoute15
    ROUTE15_WEST_ENTRANCE_1F = (24, 0)
    ROUTE15_WEST_ENTRANCE_2F = (24, 1)

    # IndoorRoute16
    ROUTE16_HOUSE = (25, 0)
    ROUTE16_NORTH_ENTRANCE_1F = (25, 1)
    ROUTE16_NORTH_ENTRANCE_2F = (25, 2)

    # IndoorRoute18
    ROUTE18_EAST_ENTRANCE_1F = (26, 0)
    ROUTE18_EAST_ENTRANCE_2F = (26, 1)

    # IndoorRoute19
    ROUTE19_UNUSED_HOUSE = (27, 0)

    # IndoorRoute22
    ROUTE22_NORTH_ENTRANCE = (28, 0)

    # IndoorRoute23
    ROUTE23_UNUSED_HOUSE = (29, 0)

    # IndoorRoute25
    ROUTE25_SEA_COTTAGE = (30, 0)

    # IndoorSevenIsland
    SEVEN_ISLAND_HOUSE_ROOM1 = (31, 0)
    SEVEN_ISLAND_HOUSE_ROOM2 = (31, 1)
    SEVEN_ISLAND_MART = (31, 2)
    SEVEN_ISLAND_POKEMON_CENTER_1F = (31, 3)
    SEVEN_ISLAND_POKEMON_CENTER_2F = (31, 4)
    SEVEN_ISLAND_UNUSED_HOUSE = (31, 5)
    SEVEN_ISLAND_HARBOR = (31, 6)

    # IndoorOneIsland
    ONE_ISLAND_POKEMON_CENTER_1F = (32, 0)
    ONE_ISLAND_POKEMON_CENTER_2F = (32, 1)
    ONE_ISLAND_HOUSE1 = (32, 2)
    ONE_ISLAND_HOUSE2 = (32, 3)
    ONE_ISLAND_HARBOR = (32, 4)

    # IndoorTwoIsland
    TWO_ISLAND_JOYFUL_GAME_CORNER = (33, 0)
    TWO_ISLAND_HOUSE = (33, 1)
    TWO_ISLAND_POKEMON_CENTER_1F = (33, 2)
    TWO_ISLAND_POKEMON_CENTER_2F = (33, 3)
    TWO_ISLAND_HARBOR = (33, 4)

    # IndoorThreeIsland
    THREE_ISLAND_HOUSE1 = (34, 0)
    THREE_ISLAND_POKEMON_CENTER_1F = (34, 1)
    THREE_ISLAND_POKEMON_CENTER_2F = (34, 2)
    THREE_ISLAND_MART = (34, 3)
    THREE_ISLAND_HOUSE2 = (34, 4)
    THREE_ISLAND_HOUSE3 = (34, 5)
    THREE_ISLAND_HOUSE4 = (34, 6)
    THREE_ISLAND_HOUSE5 = (34, 7)

    # IndoorFourIsland
    FOUR_ISLAND_POKEMON_DAY_CARE = (35, 0)
    FOUR_ISLAND_POKEMON_CENTER_1F = (35, 1)
    FOUR_ISLAND_POKEMON_CENTER_2F = (35, 2)
    FOUR_ISLAND_HOUSE1 = (35, 3)
    FOUR_ISLAND_LORELEIS_HOUSE = (35, 4)
    FOUR_ISLAND_HARBOR = (35, 5)
    FOUR_ISLAND_HOUSE2 = (35, 6)
    FOUR_ISLAND_MART = (35, 7)

    # IndoorFiveIsland
    FIVE_ISLAND_POKEMON_CENTER_1F = (36, 0)
    FIVE_ISLAND_POKEMON_CENTER_2F = (36, 1)
    FIVE_ISLAND_HARBOR = (36, 2)
    FIVE_ISLAND_HOUSE1 = (36, 3)
    FIVE_ISLAND_HOUSE2 = (36, 4)

    # IndoorSixIsland
    SIX_ISLAND_POKEMON_CENTER_1F = (37, 0)
    SIX_ISLAND_POKEMON_CENTER_2F = (37, 1)
    SIX_ISLAND_HARBOR = (37, 2)
    SIX_ISLAND_HOUSE = (37, 3)
    SIX_ISLAND_MART = (37, 4)

    # IndoorThreeIslandRoute
    THREE_ISLAND_HARBOR = (38, 0)

    # IndoorFiveIslandRoute
    FIVE_ISLAND_RESORT_GORGEOUS_HOUSE = (39, 0)

    # IndoorTwoIslandRoute
    TWO_ISLAND_CAPE_BRINK_HOUSE = (40, 0)

    # IndoorSixIslandRoute
    SIX_ISLAND_WATER_PATH_HOUSE1 = (41, 0)
    SIX_ISLAND_WATER_PATH_HOUSE2 = (41, 1)

    # IndoorSevenIslandRoute
    SEVEN_ISLAND_SEVAULT_CANYON_HOUSE = (42, 0)

    def __eq__(self, other):
        # So (3,0) == MapFRLG.PALLET_TOWN
        if _might_be_map_coordinates(other):
            return self.value == other
        elif isinstance(other, MapFRLG):
            return self.value == other.value
        return NotImplemented

    def __contains__(self, item):
        # e.g. if item is a MapLocation object with .map_group, .map_number
        # you can do item in MapFRLG.PALLET_TOWN. Skipping for now.
        return NotImplemented
    
    def __hash__(self):
    # We must define this to remain hashable after overriding __eq__.
        return hash(self.value)

    @property
    def group(self):
        return self.value[0]

    @property
    def number(self):
        return self.value[1]

    @property
    def pretty_name(self) -> str:
        """
        You can also implement that fancy text replacement
        from pokebot-gen3 if you want. This is just an example.
        """
        name = self.name.replace("_", " ").title()
        return name
